import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
// import { AuthProvider } from "./context/AuthContext";
import { AOSInit } from "./utils/AOS";
import { AuthProvider } from "./context/AuthContext";

const poppins = Poppins({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "CourseSphere",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AOSInit />
      <head>{/* <ThemeModeScript /> */}</head>
      <body className={`${poppins.variable} antialiased`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
