import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
// import { ThemeModeScript } from "flowbite-react";
import { MyNavbar } from "./components/Navbar";

const poppins = Poppins({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <ThemeModeScript /> */}
        </head>
      <body className={`${poppins.variable} antialiased`}>
        <MyNavbar />
        {children}
      </body>
    </html>
  );
}
