import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
// import { ThemeModeScript } from "flowbite-react";
import { MyNavbar } from "./components/Navbar";
import { AOSInit } from "./utils/AOS";

const poppins = Poppins({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "CourseSphere",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AOSInit />
      <head>{/* <ThemeModeScript /> */}</head>
      <body className={`${poppins.variable} antialiased`}>
        <MyNavbar />
        {children}
      </body>
    </html>
  );
}
