-- CREATE DATABASE
CREATE DATABASE IF NOT EXISTS COURSESPHERE;
USE COURSESPHERE;

-- DEPARTMENT TABLE
CREATE TABLE DEPARTMENT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(100) NOT NULL,
    AMOUNT_PER_CREDIT DECIMAL(10,2) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- HOD (HEAD OF DEPARTMENT) TABLE
CREATE TABLE HOD (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    DEPARTMENT_ID INT NOT NULL,
    STATUS  BOOL DEFAULT 1,
    PHONE VARCHAR(20),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);

-- ADVISOR TABLE
CREATE TABLE ADVISOR (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    DEPARTMENT_ID INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);

-- STUDENT TABLE
CREATE TABLE STUDENT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    REGISTRATION_NUMBER VARCHAR(50) NOT NULL UNIQUE,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    DEPARTMENT_ID INT NOT NULL,
    SESSION VARCHAR(10),
    MOBILE VARCHAR(20),
    STATUS BOOL DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);

-- ADMIN TABLE
CREATE TABLE ADMIN (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- COURSE TABLE (WITHOUT INSTRUCTOR_ID INITIALLY TO AVOID CIRCULAR REFERENCE)
CREATE TABLE COURSE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    CODE VARCHAR(20) NOT NULL UNIQUE,
    CREDIT DECIMAL(3,1) NOT NULL,
    DEPARTMENT_ID INT NOT NULL,
    STATUS BOOL DEFAULT 1,
    INSTRUCTOR_ID INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (INSTRUCTOR_ID) REFERENCES INSTRUCTOR(ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);

-- INSTRUCTOR TABLE (NOW COURSE TABLE ALREADY EXISTS)
CREATE TABLE INSTRUCTOR (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DEPARTMENT_ID INT NOT NULL,
    COURSE_ID INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID)
);

-- ADD INSTRUCTOR_ID COLUMN TO COURSE TABLE AFTER INSTRUCTOR IS CREATED
ALTER TABLE COURSE
ADD COLUMN INSTRUCTOR_ID INT NOT NULL,
ADD FOREIGN KEY (INSTRUCTOR_ID) REFERENCES INSTRUCTOR(ID);

-- PREREQUISITE TABLE
CREATE TABLE PREREQUISITE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    COURSE_ID INT NOT NULL,
    PREREQ_COURSE_ID INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID),
    FOREIGN KEY (PREREQ_COURSE_ID) REFERENCES COURSE(ID),
    UNIQUE (COURSE_ID, PREREQ_COURSE_ID)
);

-- COURSE CART TABLE
CREATE TABLE COURSE_CART (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_ID INT NOT NULL,
    COURSE_ID INT NOT NULL,
    SEMESTER VARCHAR(50) NOT NULL,
    ADDED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID),
    UNIQUE (STUDENT_ID, COURSE_ID, SEMESTER)
);

-- REGISTRATION DEADLINE TABLE
CREATE TABLE REGISTRATION_DEADLINE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SEMESTER VARCHAR(50) NOT NULL,
    DEADLINE_DATE DATE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- REGISTRATION BUNDLE TABLE
CREATE TABLE REGISTRATION_BUNDLE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_ID INT NOT NULL,
    SEMESTER VARCHAR(50) NOT NULL,
    STATUS ENUM('PENDING', 'PARTIALLY_APPROVED', 'APPROVED', 'REJECTED', 'COMPLETED') DEFAULT 'PENDING',
    HOD_APPROVAL BOOLEAN DEFAULT FALSE,
    ADVISOR_APPROVAL BOOLEAN DEFAULT FALSE,
    SUBMITTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PAYMENT_STATUS ENUM('PENDING', 'PAID', 'PARTIALLY_PAID', 'WAIVED') DEFAULT 'PENDING',
    TOTAL_AMOUNT DECIMAL(10,2) DEFAULT 0.00,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID),
    UNIQUE (STUDENT_ID, SEMESTER)
);

-- COURSE REGISTRATION TABLE
CREATE TABLE COURSE_REGISTRATION (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    BUNDLE_ID INT NOT NULL,
    COURSE_ID INT NOT NULL,
    ADVISOR_ID INT,
    STATUS ENUM('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED') DEFAULT 'PENDING',
    ADVISOR_COMMENT TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BUNDLE_ID) REFERENCES REGISTRATION_BUNDLE(ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID),
    FOREIGN KEY (ADVISOR_ID) REFERENCES ADVISOR(ID),
    UNIQUE (BUNDLE_ID, COURSE_ID)
);

-- PAYMENT TABLE
CREATE TABLE PAYMENT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    BUNDLE_ID INT NOT NULL,
    AMOUNT DECIMAL(10,2) NOT NULL,
    STATUS ENUM('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED') DEFAULT 'PENDING',
    PAYMENT_DATE TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BUNDLE_ID) REFERENCES REGISTRATION_BUNDLE(ID)
);

-- NOTICE TABLE
CREATE TABLE NOTICE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    CREATOR_ID INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CREATOR_ID) REFERENCES HOD(ID)
);

-- REGISTERED COURSES TABLE
CREATE TABLE REGISTERED_COURSES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    COURSE_ID INT NOT NULL,
    STUDENT_ID INT NOT NULL,
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID)
);

-- DEADLINES TABLE
CREATE TABLE DEADLINES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(100),
    PRIORITY ENUM('URGENT'),
    DESCRIPTION VARCHAR(255),
    DEADLINE_DATE DATE
);

-- EXAM CONTROLLER TABLE
CREATE TABLE EXAM_CONTROLLER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    PHONE VARCHAR(20),
    STATUS BOOL DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE RESULTS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_ID INT NOT NULL,
    COURSE_ID INT NOT NULL,
    GRADE ENUM('A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'D', 'F') NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID)
);

-- ACCOUNTS ADMIN TABLE
CREATE TABLE ACCOUNTS_ADMIN (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    PHONE VARCHAR(20),
    STATUS BOOL DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
